services:
  mysql:
    image: mysql:8.0
    container_name: eepz-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eepzdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping --silent --protocol=TCP -h mysql -uroot -p$root" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - eepz-network

  analysis-api:
    build: ./Relevantz.EEPZ.AnalysisApi
    container_name: eepz-analysis-api
    restart: always
    ports:
      - "5111:5111"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  auth-api:
    build: ./Relevantz.EEPZ.AuthApi
    container_name: eepz-auth-api
    restart: always
    ports:
      - "5101:5101"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5101

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  feedback-api:
    build: ./Relevantz.EEPZ.FeedbackApi
    container_name: eepz-feedback-api
    restart: always
    ports:
      - "5102:5102"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5102

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  goal-api:
    build: ./Relevantz.EEPZ.GoalApi
    container_name: eepz-goal-api
    restart: always
    ports:
      - "5103:5103"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5103

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  hr-operations-api:
    build: ./Relevantz.EEPZ.HrOpsApi
    container_name: eepz-hr-operations-api
    restart: always
    ports:
      - "5104:5104"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5104

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  internal-opportunity-api:
    build: ./Relevantz.EEPZ.InternalOpportunityAPI
    container_name: eepz-internal-opportunity-api
    restart: always
    ports:
      - "5105:5105"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5105

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  lnd-api:
    build: ./Relevantz.EEPZ.LnDApi
    container_name: eepz-lnd-api
    restart: always
    ports:
      - "5106:5106"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5106

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  meeting-api:
    build: ./Relevantz.EEPZ.MeetingsApi
    container_name: eepz-meeting-api
    restart: always
    ports:
      - "5107:5107"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5107

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  mom-api:
    build: ./Relevantz.EEPZ.MoMApi
    container_name: eepz-mom-api
    restart: always
    ports:
      - "5112:5112"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5112

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  performance-api:
    build: ./Relevantz.EEPZ.PerformanceMgmtApi
    container_name: eepz-performance-api
    restart: always
    ports:
      - "5108:5108"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5108

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  roles-api:
    build: ./Relevantz.EEPZ.PerformanceMgmtRolesApi
    container_name: eepz-roles-api
    restart: always
    ports:
      - "5113:5113"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5113

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  proj-management-api:
    build: ./Relevantz.EEPZ.ProjMgmtApi
    container_name: eepz-proj-management-api
    restart: always
    ports:
      - "5109:5109"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5109

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  rewards-api:
    build: ./Relevantz.EEPZ.RewardsApi
    container_name: eepz-rewards-api
    restart: always
    ports:
      - "5114:5114"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5114

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

  sla-api:
    build: ./Relevantz.EEPZ.SLAApi
    container_name: eepz-sla-api
    restart: always
    ports:
      - "5110:5110"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=eepzdb;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:5110

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/Logs
    networks:
      - eepz-network

volumes:
  mysql_data:

networks:
  eepz-network:
    driver: bridge
