namespace Relevantz.EEPZ.Common.DTOs
{
    /// <summary>
    /// Represents metadata for a file stored in MongoDB GridFS
    /// </summary>
    public class FileMetadata
    {
        /// <summary>
        /// MongoDB ObjectId (24-character hex string)
        /// </summary>
        public string FileId { get; set; } = string.Empty;

        /// <summary>
        /// Original filename with extension
        /// </summary>
        public string FileName { get; set; } = string.Empty;

        /// <summary>
        /// File size in bytes
        /// </summary>
        public long FileSize { get; set; }

        /// <summary>
        /// MIME content type (e.g., "application/pdf", "image/jpeg")
        /// </summary>
        public string ContentType { get; set; } = string.Empty;

        /// <summary>
        /// Date and time when file was uploaded to GridFS (UTC)
        /// </summary>
        public DateTime UploadDate { get; set; }

        /// <summary>
        /// Logical subfolder for organization (e.g., "goals/attachments")
        /// </summary>
        public string SubFolder { get; set; } = string.Empty;

        /// <summary>
        /// MD5 hash of file content (automatically generated by GridFS)
        /// </summary>
        public string? MD5Hash { get; set; }

        /// <summary>
        /// Number of chunks the file is divided into
        /// </summary>
        public int ChunkCount { get; set; }

        /// <summary>
        /// Size of each chunk in bytes (default: 1MB)
        /// </summary>
        public int ChunkSize { get; set; }
    }
}
